name: Integration Tests for First Comment Workflow

on:
  push:
    paths:
      - '.github/workflows/on-first-comment.yml'

jobs:
  run-integration-tests:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
      repository-projects: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Authenticate GH CLI
        run: echo "${{ secrets.GH_TOKEN }}" | gh auth login --with-token

      - name: Create first test issue
        run: |
          echo "Creating Issue No Status..."
          issue1_url=$(gh issue create -t "Issue No Status" -b "Test issue for Issue No Status")
          issue1_number=$(echo "$issue1_url" | sed 's/.*\/\([0-9]\+\)$/\1/')
          echo "$issue1_number" > issue_numbers.txt
          gh issue view "$issue1_number" --json number,id > "issue1.json"

      - name: Create second test issue
        run: |
          echo "Creating Issue Todo..."
          issue2_url=$(gh issue create -t "Issue Todo" -b "Test issue for Issue Todo")
          issue2_number=$(echo "$issue2_url" | sed 's/.*\/\([0-9]\+\)$/\1/')
          echo "$issue2_number" >> issue_numbers.txt
          gh issue view "$issue2_number" --json number,id > "issue2.json"

      - name: Create third test issue
        run: |
          echo "Creating Issue Blocked..."
          issue3_url=$(gh issue create -t "Issue Blocked" -b "Test issue for Issue Blocked")
          issue3_number=$(echo "$issue3_url" | sed 's/.*\/\([0-9]\+\)$/\1/')
          echo "$issue3_number" >> issue_numbers.txt
          gh issue view "$issue3_number" --json number,id > "issue3.json"

      - name: Extract issue info
        id: extract_info
        run: |
          mapfile -t numbers < issue_numbers.txt
          echo "issue1_number=${numbers[0]}" >> $GITHUB_OUTPUT
          echo "issue2_number=${numbers[1]}" >> $GITHUB_OUTPUT
          echo "issue3_number=${numbers[2]}" >> $GITHUB_OUTPUT

      - name: Assign issues to Project and set statuses
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          project_id="PVT_kwHOBM2RHM4A_swG"
          echo "Using project ID: $project_id"

          # Add issues to project using --url instead of --content-id
          issue1_num=$(jq -r '.number' "issue1.json")
          issue2_num=$(jq -r '.number' "issue2.json") 
          issue3_num=$(jq -r '.number' "issue3.json")
          
          echo "Adding issue #$issue1_num to project"
          gh project item-add 3 --owner tsenturion --url "https://github.com/tsenturion/inueco/issues/$issue1_num" || echo "Failed to add issue1"
          
          echo "Adding issue #$issue2_num to project"
          gh project item-add 3 --owner tsenturion --url "https://github.com/tsenturion/inueco/issues/$issue2_num" || echo "Failed to add issue2"
          
          echo "Adding issue #$issue3_num to project"
          gh project item-add 3 --owner tsenturion --url "https://github.com/tsenturion/inueco/issues/$issue3_num" || echo "Failed to add issue3"

          # Get field IDs first
          echo "Getting field information..."
          gh project field-list 3 --owner tsenturion --format json > fields.json
          cat fields.json
          
          status_field_id=$(jq -r '.fields[] | select(.name=="Status") | .id' fields.json)
          echo "Status field ID: $status_field_id"
          
          # Get option IDs for Status field values
          todo_option_id=$(jq -r '.fields[] | select(.name=="Status") | .options[] | select(.name=="Todo") | .id' fields.json)
          blocked_option_id=$(jq -r '.fields[] | select(.name=="Status") | .options[] | select(.name=="Blocked") | .id' fields.json)
          
          echo "Todo option ID: $todo_option_id"
          echo "Blocked option ID: $blocked_option_id"

          # Set statuses using correct project item IDs (not issue IDs)
          if [ -n "$status_field_id" ] && [ -n "$todo_option_id" ]; then
            # Get project item ID for issue2
            issue2_num=$(jq -r '.number' "issue2.json")
            echo "Getting project items for issue #$issue2_num"
            gh project item-list 3 --owner tsenturion --format json > project_items.json
            echo "Project items structure:"
            cat project_items.json | head -20
            
            # Try different selectors to find the right structure
            project_item2_id=$(jq -r ".items[] | select(.content.number == $issue2_num) | .id" project_items.json 2>/dev/null || \
                              jq -r ".[] | select(.content.number == $issue2_num) | .id" project_items.json 2>/dev/null || \
                              jq -r ".items[] | select(.content.issue.number == $issue2_num) | .id" project_items.json 2>/dev/null || echo "")
            
            echo "Setting Todo status for issue2 (project item ID: $project_item2_id)"
            if [ -n "$project_item2_id" ] && [ "$project_item2_id" != "null" ] && [ "$project_item2_id" != "" ]; then
              gh project item-edit --project-id "$project_id" --id "$project_item2_id" --field-id "$status_field_id" --single-select-option-id "$todo_option_id" || echo "Failed to set Todo status"
            else
              echo "Could not find project item ID for issue2"
            fi
          fi
          
          if [ -n "$status_field_id" ] && [ -n "$blocked_option_id" ]; then
            # Get project item ID for issue3
            issue3_num=$(jq -r '.number' "issue3.json")
            echo "Getting project items for issue #$issue3_num"
            
            # Try different selectors to find the right structure
            project_item3_id=$(jq -r ".items[] | select(.content.number == $issue3_num) | .id" project_items.json 2>/dev/null || \
                              jq -r ".[] | select(.content.number == $issue3_num) | .id" project_items.json 2>/dev/null || \
                              jq -r ".items[] | select(.content.issue.number == $issue3_num) | .id" project_items.json 2>/dev/null || echo "")
            
            echo "Setting Blocked status for issue3 (project item ID: $project_item3_id)"
            if [ -n "$project_item3_id" ] && [ "$project_item3_id" != "null" ] && [ "$project_item3_id" != "" ]; then
              gh project item-edit --project-id "$project_id" --id "$project_item3_id" --field-id "$status_field_id" --single-select-option-id "$blocked_option_id" || echo "Failed to set Blocked status"
            else
              echo "Could not find project item ID for issue3"
            fi
          fi

      - name: Add first comment to all issues
        run: |
          while read -r num; do
            if [ -n "$num" ]; then
              gh issue comment "$num" -b "First test comment"
            fi
          done < issue_numbers.txt

      - name: Wait for action to apply
        run: sleep 30

      - name: Validate expected changes
        run: |
          validate_issue() {
            local number=$1
            local expect_assignee=$2
            local expect_status=$3
            local description=$4

            echo "Checking $description (#$number)..."

            assignees=$(gh issue view "$number" --json assignees | jq -r '.assignees[].login // empty')
            status=$(gh project item-list --owner tsenturion --format json --project 3 2>/dev/null | jq -r ".items[] | select(.content.number == $number) | .status // \"\"" || echo "")

            echo "Found assignees: '$assignees'"
            echo "Found status: '$status'"

            if [ "$assignees" = "$expect_assignee" ]; then
              echo "✅ Assignee OK ($assignees)"
            else
              echo "❌ Assignee mismatch: '$assignees' != '$expect_assignee'"
              exit 1
            fi

            # Check status only if we expect a specific one
            if [ -n "$expect_status" ] && [ "$expect_status" != "" ]; then
              if [ "$status" = "$expect_status" ]; then
                echo "✅ Status OK ($status)"
              else
                echo "❌ Status mismatch: '$status' != '$expect_status'"
                exit 1
              fi
            fi
          }

          issue1=${{ steps.extract_info.outputs.issue1_number }}
          issue2=${{ steps.extract_info.outputs.issue2_number }}
          issue3=${{ steps.extract_info.outputs.issue3_number }}

          validate_issue "$issue1" "tsenturion" "" "Issue No Status"
          validate_issue "$issue2" "tsenturion" "Todo" "Issue Todo" 

          # Issue 3 (Blocked) must remain unchanged - no assignee, keep Blocked status
          echo "Checking Issue Blocked (#$issue3)..."
          blocked_assignee_count=$(gh issue view "$issue3" --json assignees | jq '.assignees | length')
          if [ "$blocked_assignee_count" -eq 0 ]; then
            echo "✅ Blocked issue has no assignees"
          else
            echo "❌ Blocked issue should have no assignees, but has $blocked_assignee_count"
            exit 1
          fi

          blocked_status=$(gh project item-list --owner tsenturion --format json --project 3 2>/dev/null | jq -r ".items[] | select(.content.number == $issue3) | .status // \"\"" || echo "")
          if [ "$blocked_status" = "Blocked" ]; then
            echo "✅ Blocked issue kept its status ($blocked_status)"
          else
            echo "❌ Blocked issue status should be 'Blocked', but is '$blocked_status'"
            exit 1
          fi

      - name: Add second comment
        run: |
          while read -r num; do
            if [ -n "$num" ]; then
              gh issue comment "$num" -b "Second test comment"
            fi
          done < issue_numbers.txt

      - name: Wait for action again
        run: sleep 30

      - name: Confirm no additional changes after second comment
        run: |
          while read -r num; do
            if [ -n "$num" ]; then
              count=$(gh issue view "$num" --json assignees | jq '.assignees | length')
              if [ "$count" -gt 1 ]; then
                echo "❌ Issue #$num has more than one assignee after second comment"
                exit 1
              fi
            fi
          done < issue_numbers.txt

          echo "✅ No changes after second comment"

      - name: Cleanup test issues
        if: always()
        run: |
          echo "Cleaning up test issues..."
          if [ -f issue_numbers.txt ]; then
            while read -r issue_num; do
              if [ -n "$issue_num" ]; then
                echo "Deleting issue #$issue_num"
                gh issue delete "$issue_num" --yes || echo "Failed to delete #$issue_num"
              fi
            done < issue_numbers.txt
          else
            echo "No issue_numbers.txt file found"
          fi